# Generated by Django 5.2.17 on 2026-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField()),
                (
                    "source_lang",
                    models.CharField(
                        help_text='Language code, or "auto" if it could not be detected',
                        max_length=15,
                    ),
                ),
                ("target_lang", models.CharField(max_length=15)),
                ("was_auto_detected", models.BooleanField(default=False)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("engine", models.CharField(default="google", max_length=20)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("cli", "Command line"),
                            ("file", "File upload"),
                        ],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_lang", "target_lang"],
                        name="translator__source__9cfa93_idx",
                    )
                ],
            },
        ),
    ]
